version: 2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: NPM_TOKEN
      - npm_publish:
          context: NPM_TOKEN
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v[\d.]+$/
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm install
      - run: npm test
  npm_publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm install
      - run: npm publish
